export const Makes = {
    "Toyota": "toyota",
    "Honda": "honda",
    "GMC": "gmc",
    "BMW": "bmw",
    "Jeep": "jeep",
    "McLaren": "mclaren",
    "Genesis": "genesis",
    "Shelby": "shelby",
    "Nissan": "nissan",
    "Mazda": "mazda",
    "Hyundai": "hyundai",
    "Lincoln": "lincoln",
    "Bentley": "bentley",
    "Ford": "ford",
    "Porsche": "porsche",
    "Cadillac": "cadillac",
    "Mercedes-Benz": "mercedes-benz",
    "Ferrari": "ferrari",
    "Dodge": "dodge",
    "Lamborghini": "lamborghini",
    "Lexus": "lexus",
    "Hummer": "hummer",
    "Chevrolet": "chevrolet",
    "Rolls-Royce": "rolls-royce",
    "Kia": "kia",
    "RAM": "ram",
    "Volkswagen": "volkswagen",
    "Aston Martin": "aston martin"
};
